/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import model.Room;
import model.Patient;
import service.RoomService;

import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author LOQ
 */
public class roompanel extends javax.swing.JPanel {
    private static final Logger logger = Logger.getLogger(roompanel.class.getName());
    
    private final Color COLOR_EMPTY = new Color(198, 239, 206); // Xanh lá nhạt 
    private final Color COLOR_AVAILABLE = new Color(255, 243, 205); // Vàng nhạt 
    private final Color COLOR_FULL = new Color(255, 205, 210); // Đỏ nhạt 
    

    private Room roomData;
    
    public roompanel() {
        initComponents();
        
        setBorder(BorderFactory.createLineBorder(Color.GRAY)); 
        setPreferredSize(new Dimension(120, 100));
    }

    public roompanel(Room room) {
        initComponents(); 
        this.roomData = room;

        setBorder(BorderFactory.createLineBorder(Color.GRAY));
        setPreferredSize(new Dimension(120, 100)); 

        displayRoomInfo(); 
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    private void displayRoomInfo() {
        if (roomData == null) return;

        
        if (numberLabel != null) numberLabel.setText("Phòng: " + roomData.getRoomNumber());
        if (typeLabel != null) typeLabel.setText(roomData.getRoomType());
        if (occupancyLabel != null) occupancyLabel.setText("Số người: " + roomData.getCurrentOccupancy() + "/" + roomData.getCapacity());
        if (statusLabel != null) statusLabel.setText("Trạng thái: " + roomData.getStatus());

        Color backgroundColor = Color.LIGHT_GRAY; 
        if (roomData.getStatus() != null) {
            String statusLower = roomData.getStatus().toLowerCase();
             if (roomData.getCurrentOccupancy() == 0) {
                 backgroundColor = COLOR_EMPTY;
             } else if (roomData.getCurrentOccupancy() < roomData.getCapacity()) {
                 backgroundColor = COLOR_AVAILABLE;
             } else { 
                 backgroundColor = COLOR_FULL;
             }
             if ("trống".equals(statusLower)) {
                 backgroundColor = COLOR_EMPTY;
             } else if ("đầy".equals(statusLower)) {
                 backgroundColor = COLOR_FULL;
             }
        }
        setBackground(backgroundColor);
        updateLabelForeground(backgroundColor); 
    }

    
    private void updateLabelForeground(Color background) {
        double luminance = (0.299 * background.getRed() + 0.587 * background.getGreen() + 0.114 * background.getBlue()) / 255;
        Color foreground = (luminance > 0.5) ? Color.BLACK : Color.WHITE;

        if (numberLabel != null) numberLabel.setForeground(foreground);
        if (typeLabel != null) typeLabel.setForeground(foreground);
        if (occupancyLabel != null) occupancyLabel.setForeground(foreground);
        if (statusLabel != null) statusLabel.setForeground(foreground);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberLabel = new javax.swing.JLabel();
        occupancyLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(120, 100));
        setLayout(new java.awt.GridLayout(4, 1));

        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText(" Phòng : ");
        numberLabel.setAlignmentX(0.5F);
        numberLabel.setFocusable(false);
        add(numberLabel);

        occupancyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupancyLabel.setText("Số người :");
        occupancyLabel.setAlignmentX(0.5F);
        add(occupancyLabel);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Trạng thái : ");
        statusLabel.setAlignmentX(0.5F);
        add(statusLabel);

        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Loại : ");
        typeLabel.setAlignmentX(0.5F);
        typeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typeLabelMouseEntered(evt);
            }
        });
        add(typeLabel);
    }// </editor-fold>//GEN-END:initComponents

    private void typeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_typeLabelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel occupancyLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
